name: flt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  provider: ^6.1.2
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
